name: CI Build (Java Sample)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'java-sbom-sample/**'
      - '.github/workflows/ci-java.yml'
  push:
    branches:
      - main
    paths:
      - 'java-sbom-sample/**'
      - '.github/workflows/ci-java.yml'

jobs:

  build-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-sbom-sample
    steps:
      - name: Checkout from SCM
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build App incl. SBOM
        run: mvn -B package
      - name: Build SBOM
        run: mvn -B org.cyclonedx:cyclonedx-maven-plugin:2.9.1:makeBom
      - name: Deploy App to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        # invoke jar:jar before deploy:deploy: https://stackoverflow.com/questions/6308162/maven-the-packaging-for-this-project-did-not-assign-a-file-to-the-build-artifac
        run: |
          mvn -B \
            jar:jar \
            deploy:deploy \
            -s $GITHUB_WORKSPACE/settings.xml
            -DaltDeploymentRepository=github::https://maven.pkg.github.com/ueberfuhr-samples/sbom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Retrieve project groupId from POM
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "PROJECT_GROUPID=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_ENV
      - name: Retrieve project artifactId from POM
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "PROJECT_ARTIFACTID=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
      - name: Retrieve project version from POM
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Deploy SBOM to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        #             -s $GITHUB_WORKSPACE/settings.xml \
        run: |
          mvn -B deploy:deploy-file \
            -Dfile=target/bom.json \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/ueberfuhr-samples/sbom \
            -DgroupId=${{ env.PROJECT_GROUPID }} \
            -DartifactId=${{ env.PROJECT_ARTIFACTID }} \
            -Dversion=${{ env.PROJECT_VERSION }}
            -Dclassifier=cyclonedx
            -Dtype=json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: 'sbom'
          path: 'target/bom.json'
      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: 'app'
          path: 'target/app.jar'
      - name: Upload POM
        uses: actions/upload-artifact@v4
        with:
          name: 'pom'
          path: 'pom.xml'
      - name: Upload Container Configuration
        uses: actions/upload-artifact@v4
        with:
          name: 'container'
          path: 'Dockerfile'

  build-container:
    needs:
      - build-app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-sbom-sample
    steps:
      - name: Restore SBOM
        uses: actions/download-artifact@v4
        with:
          name: 'sbom'
          path: 'target'
      - name: Restore App
        uses: actions/download-artifact@v4
        with:
          name: 'app'
          path: 'target'
      - name: Restore POM
        uses: actions/download-artifact@v4
        with:
          name: 'pom'
      - name: Restore Container Configuration
        uses: actions/download-artifact@v4
        with:
          name: 'container'
      # (optionally) https://github.com/docker/buildx
      # (optionally) https://github.com/docker/metadata-action
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Retrieve project version from POM
        run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Show extracted Maven project version
        run: echo 'Project version is ${{ env.PROJECT_VERSION }}'
      - name: Build Container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: |
            ralfueberfuhr/java-sbom-sample:latest
            ralfueberfuhr/java-sbom-sample:${{ env.PROJECT_VERSION }}
          labels: |
            repository=${{ github.repositoryUrl }}
          push: ${{ github.event_name != 'pull_request' }}
      - name: Write Summary
        run: echo "Successfully built container image 'ralfueberfuhr/java-sbom-sample:${{ env.PROJECT_VERSION }}'" >> $GITHUB_STEP_SUMMARY
