name: CI Build (Quarkus Sample)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'quarkus-sbom-sample/**'
      - '.github/workflows/ci-quarkus.yml'
  push:
    branches:
      - main
    paths:
      - 'quarkus-sbom-sample/**'
      - '.github/workflows/ci-quarkus.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write # GitHub packages
  pull-requests: write

defaults:
  run:
    working-directory: 'quarkus-sbom-sample'

jobs:

  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from SCM
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build App
        run: mvn -B package
      - name: Build SBOM
        run: mvn -B quarkus:dependency-sbom -Dquarkus.dependency.sbom.output-file=target/bom.json
      - name: Deploy App to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        # invoke jar:jar before deploy:deploy: https://stackoverflow.com/questions/6308162/maven-the-packaging-for-this-project-did-not-assign-a-file-to-the-build-artifac
        run: |
          mvn -B \
            jar:jar \
            deploy:deploy \
            -DaltDeploymentRepository=github::https://maven.pkg.github.com/ueberfuhr-samples/sbom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Retrieve project groupId from POM
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "PROJECT_GROUPID=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_ENV
      - name: Retrieve project artifactId from POM
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "PROJECT_ARTIFACTID=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
      - name: Retrieve project version from POM
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Deploy SBOM to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          mvn -B deploy:deploy-file \
            -Dfile=target/bom.json \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/ueberfuhr-samples/sbom \
            -DgroupId=${{ env.PROJECT_GROUPID }} \
            -DartifactId=${{ env.PROJECT_ARTIFACTID }} \
            -Dversion=${{ env.PROJECT_VERSION }} \
            -Dclassifier=cyclonedx \
            -Dtype=json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: 'sbom'
          path: 'quarkus-sbom-sample/target/bom.json'
      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: 'app'
          path: 'quarkus-sbom-sample/target/quarkus-app/**'
      - name: Upload POM
        uses: actions/upload-artifact@v4
        with:
          name: 'pom'
          path: 'quarkus-sbom-sample/pom.xml'
      - name: Upload Container Configuration
        uses: actions/upload-artifact@v4
        with:
          name: 'container'
          path: 'quarkus-sbom-sample/Dockerfile'

  build-container:
    needs:
      - build-app
    runs-on: ubuntu-latest
    steps:
      - name: Restore SBOM
        uses: actions/download-artifact@v4
        with:
          name: 'sbom'
          path: 'quarkus-sbom-sample/target'
      - name: Restore App
        uses: actions/download-artifact@v4
        with:
          name: 'app'
          path: 'quarkus-sbom-sample/target/quarkus-app'
      - name: Restore POM
        uses: actions/download-artifact@v4
        with:
          name: 'pom'
          path: 'quarkus-sbom-sample'
      - name: Restore Container Configuration
        uses: actions/download-artifact@v4
        with:
          name: 'container'
          path: 'quarkus-sbom-sample'
      # (optionally) https://github.com/docker/buildx
      # (optionally) https://github.com/docker/metadata-action
      - name: Login to Docker Hub
        # we need it for Docker Scout!
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Retrieve project version from POM
        run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Show extracted Maven project version
        run: echo 'Project version is ${{ env.PROJECT_VERSION }}'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Container incl. SBOM (PR)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: 'spring-sbom-sample'
          file: 'spring-sbom-sample/Dockerfile'
          tags: |
            ralfueberfuhr/spring-sbom-sample:${{ env.PROJECT_VERSION }}-${{ github.run_id }}
          push: false
          load: true # load to local Docker daemon to find it in the next step - in conflict with "platforms"
      - name: Build Container incl. SBOM (main)
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm64/v8 # in conflict to "load"
          provenance: mode=max
          context: 'quarkus-sbom-sample'
          file: 'quarkus-sbom-sample/Dockerfile'
          tags: |
            ralfueberfuhr/quarkus-sbom-sample:latest
            ralfueberfuhr/quarkus-sbom-sample:${{ env.PROJECT_VERSION }}
          labels: |
            repository=${{ github.repositoryUrl }}
          sbom: true
          push: true
      - name: Check vulnerabilities (PR)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ralfueberfuhr/quarkus-sbom-sample:${{ env.PROJECT_VERSION }}-${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check vulnerabilities (main)
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ralfueberfuhr/quarkus-sbom-sample:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Write Summary
        run: echo "Successfully built container image 'ralfueberfuhr/quarkus-sbom-sample:${{ env.PROJECT_VERSION }}'" >> $GITHUB_STEP_SUMMARY
